services:

  server:
    image: websocket_serial_converter
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - /dev:/dev
    ports:
      - "8800:8800"
    privileged: true